### PR TITLE
Dockerize OpenRefine

### PR DESCRIPTION
**Pull request by frafra**
Code from https://github.com/NINAnor/openrefine.

### CODE REVIEW

**Review by wetneb — APPROVED** [review]
Amazing, thanks a lot! Let me add you to the repository so that you are able to make further changes and review contributions here.

**Comment by frafra** [comment]
Great!
The container is built, but not shared, as it is not public. I will start to use the container produced here as soon as they will be made available :)

**Comment by wetneb** [comment]
How do we make it public?

**Comment by frafra** [comment]
I am not an admin of the repository, so I cannot do it.
In the right column, you should see the package listed; click on that, then go to package settings, and change package visibility.

**Comment by tfmorris** [comment]
Did we make a conscious decision to use the Github Container Registry over Docker Hub? What are the pros/cons?

Also, I know that this has already been merged, but it might be worth considering whether `containers` is too generic a name.

**Comment by frafra** [comment]
It is integrated with GitHub, which can make it easier to handle users' permissions, but feel free to use whatever you like the most.
The name of the repository can be changed, and the pipeline executed again, so the name of the container reflects the name. You probably want to use something different from `env.IMAGE_NAME`, since the image would be named "openrefine/containers", which seems a bit weird :)

**Comment by tfmorris** [comment]
The pull limits that DockerHub introduced a couple of years ago are a little annoying, but, in practice, shouldn't affect most people and I think it's a more visible and well known registry. The fine-grained Github permissions could be useful in other contexts, but here it's an artifact that we want public and widely available, so I don't think permissions are an issue.

`openrefine/openrefine` is probably a better base name. We can than add variants for other containers containing additional components.

**Pull request merged**
